### ISSUE TITLE
最新系统稳定性询问

### ISSUE THREAD

**Issue by unixc3t** [coder-cheng/AsRockZ390m-itx#2]
我在远景看到楼主这个配置,我想问问现在也还稳定吗,我也打算配置一套楼主这个

**Comment by coder-cheng** [comment]
一直在用，差不多半年了吧，感觉没什么问题

**Comment by unixc3t** [comment]
现在用的是最新的macos版本吗,系统也可以在线升级吗

**Comment by coder-cheng** [comment]
我的系统没有进行升级操作，没试过，感觉14.6是稳定版，15版本系统还在开发。打算出16了，15系列系统稳定一些再进行升级。

**Comment by unixc3t** [comment]
明白了.谢谢您,

**Comment by wkj89** [comment]
> 现在用的是最新的macos版本吗,系统也可以在线升级吗

同主板  我现在已经是11.2.1了
